version: "3.9"
services:
  rasa-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5005:5005
    volumes:
      - ./:/app
      - ./connectors:/app/connectors
      - ./.config:/.config
      - ./.cache:/.cache
