FROM rasa/rasa-sdk:2.4.0

WORKDIR /app

COPY ./actions /app/actions

EXPOSE 5055

COPY ./actions/requirements-actions.txt ./requirements.txt

USER root

RUN apt-get update -qq && \
    apt-get install -y curl jq && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN apt-get update && apt-get dist-upgrade -y --no-install-recommends

RUN pip install -r requirements.txt

ENTRYPOINT [ "python3" ]

USER 1001

CMD ["-m", "rasa_sdk", "--actions", "actions"]
