version: "3.9"

volumes:
  database:

services:
  action-server:
    restart: always
    environment:
    - GOOGLE_MAPS_API_KEY
    build:
      context: .
      dockerfile: Dockerfile.action
    ports: 
      - 5055:5055

  main:
    restart: always
    environment:
    - MONGODB_URL
    - ACTION_URL
    - LINE_CHANNEL_SECRET
    - LINE_CHANNEL_ACCESS_TOKEN
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5005:5005
    volumes:
      - ./:/app
      - ./.config:/.config
      - ./.cache:/.cache
  
  mongo:
    image: mongo:4.4
    volumes:
      - database:/data/db
    ports:
      - 27017:27017
    restart: always
