on:
  push:
    branches:
      - main

name: CI / CD

jobs:
  build_and_push_action_server:
    name: Build and Push Action Server to DockerHub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build Action Server image
      uses: RasaHQ/rasa-action-server-gha@v1.0.3
      with:
        rasa_sdk_version: '2.4.0'
        requirements_file: actions/requirements-actions.txt
        docker_image_name: 'rid1hady/senna-action-server'
        docker_registry_login: ${{ secrets.DOCKER_HUB_LOGIN }}
        docker_registry_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker_image_tag: ${{ github.sha }}
